// This file was auto-generated by ML.NET Model Builder.
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace SampleRegression.ConsoleApp
{
    public partial class SampleRegression
    {
        /// <summary>
        /// model input class for SampleRegression.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [LoadColumn(1)]
            [ColumnName(@"Age")]
            public float Age { get; set; }

            [LoadColumn(2)]
            [ColumnName(@"Gender")]
            public string Gender { get; set; }

            [LoadColumn(3)]
            [ColumnName(@"Ethnicity")]
            public string Ethnicity { get; set; }

            [LoadColumn(4)]
            [ColumnName(@"Department")]
            public string Department { get; set; }

            [LoadColumn(5)]
            [ColumnName(@"JobTitle")]
            public string JobTitle { get; set; }

            [LoadColumn(6)]
            [ColumnName(@"PerformanceScore")]
            public float PerformanceScore { get; set; }

            [LoadColumn(7)]
            [ColumnName(@"TenureYears")]
            public float TenureYears { get; set; }

            [LoadColumn(8)]
            [ColumnName(@"DisabilityStatus")]
            public bool DisabilityStatus { get; set; }

            [LoadColumn(9)]
            [ColumnName(@"VeteranStatus")]
            public bool VeteranStatus { get; set; }

            [LoadColumn(10)]
            [ColumnName(@"Location")]
            public string Location { get; set; }

            [LoadColumn(11)]
            [ColumnName(@"LGBTStatus")]
            public bool LGBTStatus { get; set; }

            [LoadColumn(12)]
            [ColumnName(@"Promotion")]
            public bool Promotion { get; set; }

            [LoadColumn(13)]
            [ColumnName(@"InclusionProgramParticipant")]
            public bool InclusionProgramParticipant { get; set; }

            [LoadColumn(14)]
            [ColumnName(@"Salary")]
            public float Salary { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for SampleRegression.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"Age")]
            public float Age { get; set; }

            [ColumnName(@"Gender")]
            public float[] Gender { get; set; }

            [ColumnName(@"Ethnicity")]
            public float[] Ethnicity { get; set; }

            [ColumnName(@"Department")]
            public float[] Department { get; set; }

            [ColumnName(@"JobTitle")]
            public float[] JobTitle { get; set; }

            [ColumnName(@"PerformanceScore")]
            public float PerformanceScore { get; set; }

            [ColumnName(@"TenureYears")]
            public float TenureYears { get; set; }

            [ColumnName(@"DisabilityStatus")]
            public float[] DisabilityStatus { get; set; }

            [ColumnName(@"VeteranStatus")]
            public float[] VeteranStatus { get; set; }

            [ColumnName(@"Location")]
            public float[] Location { get; set; }

            [ColumnName(@"LGBTStatus")]
            public float[] LGBTStatus { get; set; }

            [ColumnName(@"Promotion")]
            public float[] Promotion { get; set; }

            [ColumnName(@"InclusionProgramParticipant")]
            public float[] InclusionProgramParticipant { get; set; }

            [ColumnName(@"Salary")]
            public float Salary { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"Score")]
            public float Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("SampleRegression.mlnet");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);


        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }
    }
}
