# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go CICD

on:
  push:
    branches: 
      - main
      - feature
  pull_request:
    branches: 
      - main
      - feature

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Build
      run: |
        go version
        cd src
        if [ ! -e *.mod ]; then
          go mod init ${GITHUB_REPOSITORY}
        fi
        go mod tidy
        go build main.go

    - name: Send slack notification
      uses: 8398a7/action-slack@v3 
      with:
          status: ${{ job.status }}
          fields:
            repo, message, commit, author, action, eventName, ref, workflow, job, took
      env:
        SLACK_WEBHOOD_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always ()

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
    steps:
    - uses: actions/checkout@v2

    - name: Deploy to Docker registry
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: mccoyale/employeedatagenerator
        tag_with_ref: true
