# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: CICD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.21', '1.23', '1.24.x' ]

    steps:
    - uses: actions/download-artifact@v4
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}
        go-version-file: 'go.mod'
        check-latest: true

    - name: Install Dependencies
      run:
        go install employeeDataGenerator
        go version
    - name: Run Build
      run: go build main.go

 #   - name: Run vet & lint
 #    run: |
 #      go vet . 
 #      golint .

#    - name: Run TestsTest
#     run: go test -v ./...

    - name: Send slack notification
      uses: 8398a7/action-slack@v3 
      with:
          status: ${{ job.status }}
          fields:
            repo, message, commit, author, action, eventName, ref, workflow, job, took
      env:
        SLACK_WEBHOOD_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always ()

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
    steps:
    - uses: actions/checkout@v2

    - name: Deploy to Docker registry
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: mccoyale/employeedatagenerator
        tag_with_ref: true
